_schema_version=1
block_usb_storage.status=DISABLE
block_usb_storage.value=all
block_printers_scanners.status=DISABLE
block_printers_scanners.value=all
block_optical_drives.status=DISABLE
block_optical_drives.value=all
permanent_device_missing_severity.status=ENABLE
permanent_device_missing_severity.value=STANDARD
