#include "DevicePolicyCompiler.h"

#include <fic/core/ProcessExecutor.h>

#include <algorithm>
#include <cerrno>
#include <chrono>
#include <cstring>
#include <fcntl.h>
#include <fstream>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <unistd.h>
#include <utility>
#include <vector>

namespace fic::device_control {
namespace {

constexpr const char* GENERATED_HEADER =
    "# Generated by FIC Device Control. DO NOT EDIT.\n"
    "# SQLite stores desired policy; this file is the active hotplug policy.\n";

std::size_t pathDepth(const std::string& path)
{
    return static_cast<std::size_t>(std::count(path.begin(), path.end(), '/'));
}

bool managedDevpath(const std::string& path)
{
    return path.rfind("/devices/", 0) == 0 && path.find_first_of("*?[") == std::string::npos;
}

std::string policyLevel(const std::string& level)
{
    if (level == "blocked") {
        return "DENY";
    }
    if (level == "permanent") {
        return "PERMANENT";
    }
    if (level == "ignored") {
        return "IGNORE";
    }
    return "ALLOW";
}

std::string attribute(const std::map<std::string, std::string>& attributes,
                      const std::string& name)
{
    const auto found = attributes.find(name);
    return found == attributes.end() ? std::string{} : found->second;
}

struct IdentityTerm {
    std::string key;
    std::string value;
};

bool addIdentityTerm(std::vector<IdentityTerm>& terms,
                     const std::string& key,
                     const std::string& value)
{
    if (value.empty() || value.find_first_of("*?[") != std::string::npos) {
        return false;
    }
    terms.push_back({key, value});
    return true;
}

bool identityTerms(const DeviceInfo& device,
                   const std::map<std::string, std::string>& attributes,
                   std::vector<IdentityTerm>& terms,
                   std::string& error)
{
    terms.clear();
    if (device.subsystem == "usb" && attribute(attributes, "DEVTYPE") == "usb_device") {
        if (!addIdentityTerm(terms, "DEVTYPE", "usb_device") ||
            !addIdentityTerm(terms, "ID_VENDOR_ID", attribute(attributes, "ID_VENDOR_ID")) ||
            !addIdentityTerm(terms, "ID_MODEL_ID", attribute(attributes, "ID_MODEL_ID")) ||
            !addIdentityTerm(terms, "ID_SERIAL", attribute(attributes, "ID_SERIAL"))) {
            error = "USB identity requires safe DEVTYPE, vendor, product and serial attributes";
            return false;
        }
        return true;
    }

    if (device.subsystem == "block") {
        const std::vector<std::string> stableKeys = {
            "DM_UUID", "ID_WWN", "ID_PART_ENTRY_UUID", "ID_FS_UUID", "ID_SERIAL"
        };
        for (const std::string& key : stableKeys) {
            const std::string value = attribute(attributes, key);
            if (!value.empty()) {
                if (!addIdentityTerm(terms, key, value)) {
                    error = "block identity attribute contains unsafe glob characters: " + key;
                    return false;
                }
                const std::string devtype = attribute(attributes, "DEVTYPE");
                if (!devtype.empty() && !addIdentityTerm(terms, "DEVTYPE", devtype)) {
                    error = "block DEVTYPE contains unsafe glob characters";
                    return false;
                }
                return true;
            }
        }
        error = "block identity requires DM_UUID, WWN, partition UUID, filesystem UUID or serial";
        return false;
    }

    error = "no safe placement-independent identity is available for subsystem " +
        device.subsystem;
    return false;
}

std::string joinRule(const std::vector<std::string>& terms)
{
    std::ostringstream out;
    for (std::size_t i = 0; i < terms.size(); ++i) {
        if (i != 0) {
            out << ", ";
        }
        out << terms[i];
    }
    out << '\n';
    return out.str();
}

bool writeAll(int fd, const std::string& data, std::string& error)
{
    std::size_t offset = 0;
    while (offset < data.size()) {
        const ssize_t written = ::write(fd, data.data() + offset, data.size() - offset);
        if (written < 0) {
            if (errno == EINTR) {
                continue;
            }
            error = std::strerror(errno);
            return false;
        }
        offset += static_cast<std::size_t>(written);
    }
    return true;
}

} // namespace

DevicePolicyCompiler::DevicePolicyCompiler(DevicePolicyCompilerOptions options)
    : options_(std::move(options))
{
}

bool DevicePolicyCompiler::escapeUdevValue(const std::string& value,
                                           std::string& escaped,
                                           std::string& error)
{
    escaped.clear();
    error.clear();
    for (const unsigned char ch : value) {
        switch (ch) {
        case '\\':
            escaped += "\\\\";
            break;
        case '"':
            escaped += "\\\"";
            break;
        case '\n':
            escaped += "\\x0a";
            break;
        case '\r':
            escaped += "\\x0d";
            break;
        case '\t':
            escaped += "\\x09";
            break;
        case '\0':
            error = "udev values cannot contain NUL";
            return false;
        default:
            if (ch < 0x20 || ch == 0x7f) {
                std::ostringstream encoded;
                encoded << "\\x" << std::hex;
                const char* digits = "0123456789abcdef";
                encoded << digits[(ch >> 4) & 0x0f] << digits[ch & 0x0f];
                escaped += encoded.str();
            } else {
                escaped.push_back(static_cast<char>(ch));
            }
        }
    }
    return true;
}

DevicePolicyCompilation DevicePolicyCompiler::compile(DB& db) const
{
    DevicePolicyCompilation result;
    if (options_.ficDickPath.empty() || options_.ficDickPath.front() != '/') {
        result.error = "fic-dick path must be absolute";
        return result;
    }

    std::vector<DeviceInfo> devices = db.getAllDevices();
    const DeviceCategoryPolicyState categories = db.getDeviceCategoryPolicyState();
    std::sort(devices.begin(), devices.end(), [](const DeviceInfo& left, const DeviceInfo& right) {
        if (pathDepth(left.devpath) != pathDepth(right.devpath)) {
            return pathDepth(left.devpath) < pathDepth(right.devpath);
        }
        if (left.subsystem != right.subsystem) {
            return left.subsystem < right.subsystem;
        }
        if (left.devpath != right.devpath) {
            return left.devpath < right.devpath;
        }
        return left.id < right.id;
    });

    std::string executable;
    std::string escapingError;
    if (!escapeUdevValue(options_.ficDickPath, executable, escapingError)) {
        result.error = "invalid fic-dick path: " + escapingError;
        return result;
    }

    std::ostringstream out;
    out << GENERATED_HEADER << "\n# FIC_START\n\n";
    out << "# REMOVE\n";
    out << "ACTION==\"remove\", SUBSYSTEM==\"usb|usbmisc|pci|block\", "
           "ENV{DEVPATH}!=\"\", RUN+=\"" << executable
        << " udev\", GOTO=\"fic_devices_end\"\n\n";
    out << "# ADD/CHANGE FILTER\n";
    out << "ACTION!=\"add|change\", GOTO=\"fic_devices_end\"\n";
    out << "SUBSYSTEM!=\"usb\", SUBSYSTEM!=\"usbmisc\", SUBSYSTEM!=\"pci\", "
           "SUBSYSTEM!=\"block\", GOTO=\"fic_devices_end\"\n";
    out << "ENV{DEVPATH}==\"\", GOTO=\"fic_devices_notify\"\n\n";
    out << "# DEFAULT ENV VARIABLES\n";
    out << "ENV{FIC_DEVICE_LEVEL}=\"UNKNOWN\", ENV{FIC_INHERITED_LEVEL}=\"UNKNOWN\", "
           "ENV{FIC_DIRECT_MATCH}=\"0\", ENV{FIC_POLICY_SOURCE}=\"global-default\"\n\n";

    out << "# INHERITED RULES\n";
    for (const DeviceInfo& device : devices) {
        if (device.children_control == "inherit" || !managedDevpath(device.devpath)) {
            continue;
        }
        std::string devpath;
        if (!escapeUdevValue(device.devpath, devpath, escapingError)) {
            result.error = "cannot escape inherited DEVPATH for device " +
                std::to_string(device.id) + ": " + escapingError;
            return result;
        }
        out << "ENV{DEVPATH}==\"" << devpath << "/*\", ENV{FIC_INHERITED_LEVEL}=\""
            << (device.children_control == "deny" ? "DENY" : "ALLOW")
            << "\", ENV{FIC_POLICY_SOURCE}=\"children:" << device.id << "\"\n";
    }

    out << "\n# CATEGORY RULES\n";
    if (categories.block_usb_storage) {
        out << "SUBSYSTEM==\"block\", ENV{ID_BUS}==\"usb\", "
               "ENV{FIC_INHERITED_LEVEL}=\"DENY\", ENV{FIC_POLICY_SOURCE}=\"dc:block_usb_storage\"\n";
        out << "SUBSYSTEM==\"usb\", ENV{ID_USB_INTERFACES}==\"*:08*\", "
               "ENV{FIC_INHERITED_LEVEL}=\"DENY\", ENV{FIC_POLICY_SOURCE}=\"dc:block_usb_storage\"\n";
    }
    if (categories.block_printers_scanners) {
        out << "SUBSYSTEM==\"usb\", ENV{ID_USB_INTERFACES}==\"*:06*|*:07*\", "
               "ENV{FIC_INHERITED_LEVEL}=\"DENY\", ENV{FIC_POLICY_SOURCE}=\"dc:block_printers_scanners\"\n";
        out << "SUBSYSTEM==\"usb\", ENV{INTERFACE}==\"6/*|7/*\", "
               "ENV{FIC_INHERITED_LEVEL}=\"DENY\", ENV{FIC_POLICY_SOURCE}=\"dc:block_printers_scanners\"\n";
    }
    if (categories.block_optical_drives) {
        out << "SUBSYSTEM==\"block\", ENV{ID_CDROM}==\"1\", "
               "ENV{FIC_INHERITED_LEVEL}=\"DENY\", ENV{FIC_POLICY_SOURCE}=\"dc:block_optical_drives\"\n";
    }

    out << "\n# DIRECT PLACEMENT RULES\n";
    for (const DeviceInfo& device : devices) {
        if (!device.control_explicit || device.ignore_hierarchy || !managedDevpath(device.devpath)) {
            continue;
        }
        std::string devpath;
        if (!escapeUdevValue(device.devpath, devpath, escapingError)) {
            result.error = "cannot escape direct DEVPATH for device " +
                std::to_string(device.id) + ": " + escapingError;
            return result;
        }
        out << "ENV{DEVPATH}==\"" << devpath << "\", ENV{FIC_DIRECT_MATCH}=\"1\", "
               "ENV{FIC_DEVICE_LEVEL}=\"" << policyLevel(device.control_level)
            << "\", ENV{FIC_POLICY_SOURCE}=\"placement:" << device.id << "\"\n";
    }

    out << "\n# DIRECT IDENTITY RULES\n";
    std::map<std::string, std::string> compiledIdentities;
    for (const DeviceInfo& device : devices) {
        if (!device.control_explicit || !device.ignore_hierarchy) {
            continue;
        }
        std::vector<IdentityTerm> identity;
        std::string identityError;
        if (!identityTerms(device, db.getDeviceAttributes(device.id), identity, identityError)) {
            result.error = "identity rule cannot be compiled for device " +
                std::to_string(device.id) + ": " + identityError;
            return result;
        }
        std::string identitySignature = device.subsystem;
        for (const IdentityTerm& term : identity) {
            identitySignature += "\n" + term.key + "=" + term.value;
        }
        const std::string level = policyLevel(device.control_level);
        const auto existingIdentity = compiledIdentities.find(identitySignature);
        if (existingIdentity != compiledIdentities.end()) {
            if (existingIdentity->second != level) {
                result.error = "conflicting direct identity rules for device " +
                    std::to_string(device.id);
                return result;
            }
            continue;
        }
        compiledIdentities.emplace(identitySignature, level);
        std::vector<std::string> terms = {"SUBSYSTEM==\"" + device.subsystem + "\""};
        for (const IdentityTerm& term : identity) {
            std::string escaped;
            if (!escapeUdevValue(term.value, escaped, escapingError)) {
                result.error = "cannot escape identity attribute " + term.key +
                    " for device " + std::to_string(device.id) + ": " + escapingError;
                return result;
            }
            terms.push_back("ENV{" + term.key + "}==\"" + escaped + "\"");
        }
        terms.push_back("ENV{FIC_DIRECT_MATCH}=\"1\"");
        terms.push_back("ENV{FIC_DEVICE_LEVEL}=\"" + level + "\"");
        terms.push_back("ENV{FIC_POLICY_SOURCE}=\"identity:" + std::to_string(device.id) + "\"");
        out << joinRule(terms);
    }

    out << "\n# POLICY DECISION\n";
    out << "ENV{FIC_DIRECT_MATCH}==\"1\", ENV{FIC_EFFECTIVE_LEVEL}=\"$env{FIC_DEVICE_LEVEL}\"\n";
    out << "ENV{FIC_DIRECT_MATCH}!=\"1\", ENV{FIC_INHERITED_LEVEL}!=\"UNKNOWN\", "
           "ENV{FIC_EFFECTIVE_LEVEL}=\"$env{FIC_INHERITED_LEVEL}\"\n";
    out << "ENV{FIC_EFFECTIVE_LEVEL}==\"\", ENV{FIC_EFFECTIVE_LEVEL}=\"ALLOW\", "
           "ENV{FIC_POLICY_SOURCE}=\"global-default\"\n";
    out << "ENV{FIC_EFFECTIVE_LEVEL}==\"PERMANENT\", ENV{FIC_CONNECTION_LEVEL}=\"ALLOW\"\n";
    out << "ENV{FIC_EFFECTIVE_LEVEL}==\"IGNORE\", ENV{FIC_CONNECTION_LEVEL}=\"ALLOW\"\n";
    out << "ENV{FIC_CONNECTION_LEVEL}==\"\", ENV{FIC_CONNECTION_LEVEL}=\"$env{FIC_EFFECTIVE_LEVEL}\"\n\n";

    out << "# SUBSYSTEM ENFORCEMENT\n";
    out << "ENV{FIC_CONNECTION_LEVEL}==\"DENY\", RUN+=\"" << executable << " enforce\"\n\n";
    out << "# NOTIFY FIC-DICK\nLABEL=\"fic_devices_notify\"\n";
    out << "RUN+=\"" << executable << " udev\"\n\n";
    out << "# FIC_END\nLABEL=\"fic_devices_end\"\n";

    result.ok = true;
    result.rules = out.str();
    return result;
}

DevicePolicyActivator::DevicePolicyActivator(DevicePolicyActivatorOptions options)
    : options_(std::move(options))
{
}

bool DevicePolicyActivator::activate(const std::string& rules, std::string& error) const
{
    error.clear();
    if (options_.activeRulesPath.empty() || !options_.activeRulesPath.is_absolute() ||
        options_.activeRulesPath.filename() != "99-fic-devices.rules") {
        error = "active udev rules path is invalid";
        return false;
    }
    std::error_code filesystemError;
    std::filesystem::create_directories(options_.activeRulesPath.parent_path(), filesystemError);
    if (filesystemError) {
        error = "cannot create udev rules directory: " + filesystemError.message();
        return false;
    }

    std::optional<std::string> previousRules;
    if (std::filesystem::is_regular_file(options_.activeRulesPath, filesystemError) &&
        !filesystemError) {
        std::ifstream previous(options_.activeRulesPath);
        previousRules = std::string(
            std::istreambuf_iterator<char>(previous),
            std::istreambuf_iterator<char>());
    }

    const std::filesystem::path temporary = options_.activeRulesPath.string() + ".tmp";
    const int fd = ::open(temporary.c_str(), O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC | O_NOFOLLOW, 0644);
    if (fd < 0) {
        error = "cannot open temporary udev rules: " + std::string(std::strerror(errno));
        return false;
    }
    if (::fchmod(fd, 0644) != 0) {
        error = "cannot set temporary udev rules permissions: " +
            std::string(std::strerror(errno));
        ::close(fd);
        ::unlink(temporary.c_str());
        return false;
    }
    bool ok = writeAll(fd, rules, error);
    if (ok && ::fsync(fd) != 0) {
        error = "cannot fsync temporary udev rules: " + std::string(std::strerror(errno));
        ok = false;
    }
    if (::close(fd) != 0 && ok) {
        error = "cannot close temporary udev rules: " + std::string(std::strerror(errno));
        ok = false;
    }
    if (!ok) {
        ::unlink(temporary.c_str());
        return false;
    }
    if (::rename(temporary.c_str(), options_.activeRulesPath.c_str()) != 0) {
        error = "cannot publish udev rules: " + std::string(std::strerror(errno));
        ::unlink(temporary.c_str());
        return false;
    }

    const int directoryFd = ::open(options_.activeRulesPath.parent_path().c_str(), O_RDONLY | O_DIRECTORY | O_CLOEXEC);
    if (directoryFd >= 0) {
        ::fsync(directoryFd);
        ::close(directoryFd);
    }

    ProcessOptions processOptions;
    processOptions.timeout = std::chrono::milliseconds(5000);
    const ProcessResult reload = ProcessExecutor::execute(
        options_.udevadmPath, {"control", "--reload-rules"}, processOptions);
    if (!reload.success()) {
        const std::string reloadError =
            "udev reload failed: " + reload.error + " " + reload.standardError;
        bool restored = false;
        if (previousRules.has_value()) {
            const int restoreFd = ::open(
                temporary.c_str(),
                O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC | O_NOFOLLOW,
                0644);
            std::string restoreError;
            if (restoreFd >= 0) {
                bool restoreOk = ::fchmod(restoreFd, 0644) == 0 &&
                    writeAll(restoreFd, previousRules.value(), restoreError) &&
                    ::fsync(restoreFd) == 0;
                if (::close(restoreFd) != 0) {
                    restoreOk = false;
                }
                if (restoreOk &&
                    ::rename(temporary.c_str(), options_.activeRulesPath.c_str()) == 0) {
                    restored = true;
                }
                if (!restored) {
                    ::unlink(temporary.c_str());
                }
            }
        } else {
            restored = ::unlink(options_.activeRulesPath.c_str()) == 0 || errno == ENOENT;
        }
        ProcessExecutor::execute(
            options_.udevadmPath, {"control", "--reload-rules"}, processOptions);
        error = reloadError + (restored
            ? "; previous rules restored"
            : "; failed to restore previous rules");
        return false;
    }
    return true;
}

} // namespace fic::device_control
