FROM debian:11

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    dpkg-dev \
    file \
    libgl1-mesa-dev \
    libsqlite3-dev \
    libssl-dev \
    libxkbcommon-dev \
    nlohmann-json3-dev \
    pkg-config \
    qt5-qmake \
    qtbase5-dev \
    qtbase5-dev-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["bash"]
