blocking_user_access_to_system_files:DISABLE:ENABLE
custom_mode_and_owner:DISABLE:[]
systemcommandlock:DISABLE:ENABLE
sudo_env_reset:DISABLE:ENABLE
sudo_passwd_tries:DISABLE:3
sudo_securepath:DISABLE:["/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin"]
sudo_timeout:DISABLE:1
