_schema_version=2
blocking_user_access_to_system_files.status=DISABLE
blocking_user_access_to_system_files.value=ENABLE
custom_mode_and_owner.status=DISABLE
custom_mode_and_owner.value=[]
systemcommandlock.status=DISABLE
systemcommandlock.value=ENABLE
sudo_env_reset.status=DISABLE
sudo_env_reset.value=ENABLE
sudo_passwd_tries.status=DISABLE
sudo_passwd_tries.value=3
sudo_securepath.status=DISABLE
sudo_securepath.value=["/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin"]
sudo_timeout.status=DISABLE
sudo_timeout.value=1
sudo_require_authentication.status=DISABLE
sudo_require_authentication.value=ENABLE
