block_usb_storage.status=DISABLE
block_usb_storage.value=false
block_printers_scanners.status=DISABLE
block_printers_scanners.value=false
block_optical_drives.status=DISABLE
block_optical_drives.value=false
