_schema_version=2
block_usb_storage.status=DISABLE
block_usb_storage.value=true
block_printers_scanners.status=DISABLE
block_printers_scanners.value=true
block_optical_drives.status=DISABLE
block_optical_drives.value=true
