_schema_version=2
password_min_length.status=DISABLE
password_min_length.value=12
password_min_classes.status=DISABLE
password_min_classes.value=3
password_history_depth.status=DISABLE
password_history_depth.value=5
password_history_enforce_for_root.status=DISABLE
password_history_enforce_for_root.value=yes
failed_authentication_attempts.status=DISABLE
failed_authentication_attempts.value=5
failed_authentication_counting_period.status=DISABLE
failed_authentication_counting_period.value=900
failed_authentication_enforce_for_root.status=DISABLE
failed_authentication_enforce_for_root.value=yes
failed_authentication_unlock_time.status=DISABLE
failed_authentication_unlock_time.value=600
sssd_offline_credentials_expiration.status=DISABLE
sssd_offline_credentials_expiration.value=30
kerberos_ticket_lifetime.status=DISABLE
kerberos_ticket_lifetime.value=36000
