screenlock_timeout.status=DISABLE
screenlock_timeout.value=10
disable_autologin.status=DISABLE
disable_autologin.value=ENABLE
disable_videodisplay_when_locked.status=DISABLE
disable_videodisplay_when_locked.value=ENABLE
lock_on_tty_switch.status=DISABLE
lock_on_tty_switch.value=ENABLE
