_schema_version=2
grub_timeout.status=DISABLE
grub_timeout.value=5
grub_cmdline_linux.status=DISABLE
grub_cmdline_linux.value=[]
grub_disable_recovery.status=DISABLE
grub_disable_recovery.value=ENABLE
screenlock_timeout.status=DISABLE
screenlock_timeout.value=10
disable_autologin.status=DISABLE
disable_autologin.value=ENABLE
disable_videodisplay_when_locked.status=DISABLE
disable_videodisplay_when_locked.value=ENABLE
lock_on_tty_switch.status=DISABLE
lock_on_tty_switch.value=ENABLE
fstab_tmp_profile.status=DISABLE
fstab_tmp_profile.value=optimal
fstab_var_tmp_profile.status=DISABLE
fstab_var_tmp_profile.value=optimal
fstab_dev_shm_profile.status=DISABLE
fstab_dev_shm_profile.value=optimal
fstab_home_profile.status=DISABLE
fstab_home_profile.value=optimal
fstab_removable_media_profile.status=DISABLE
fstab_removable_media_profile.value=optimal
fstab_var_log_secure_options.status=DISABLE
fstab_var_log_secure_options.value=ENABLE
fstab_var_log_audit_secure_options.status=DISABLE
fstab_var_log_audit_secure_options.value=ENABLE
fstab_boot_profile.status=DISABLE
fstab_boot_profile.value=minimal
fstab_boot_efi_profile.status=DISABLE
fstab_boot_efi_profile.value=minimal
fstab_srv_profile.status=DISABLE
fstab_srv_profile.value=minimal
fstab_opt_profile.status=DISABLE
fstab_opt_profile.value=ENABLE
