_schema_version=1
kernel_exec_shield_enable.status=DISABLE
kernel_exec_shield_enable.value=ENABLE
kernel_dmesg_restrict.status=DISABLE
kernel_dmesg_restrict.value=ENABLE
fs_file_max_limit.status=DISABLE
fs_file_max_limit.value=786144
fs_protected_hardlinks.status=DISABLE
fs_protected_hardlinks.value=ENABLE
ipv4_default_accept_redirects_disable.status=DISABLE
ipv4_default_accept_redirects_disable.value=ENABLE
ipv4_default_rp_filter_enable.status=DISABLE
ipv4_default_rp_filter_enable.value=1
ipv4_default_send_redirects_disable.status=DISABLE
ipv4_default_send_redirects_disable.value=ENABLE
ipv6_all_accept_redirects_disable.status=DISABLE
ipv6_all_accept_redirects_disable.value=ENABLE
ipv6_default_accept_redirects_disable.status=DISABLE
ipv6_default_accept_redirects_disable.value=ENABLE
ipv6_packet_forwarding_disable.status=DISABLE
ipv6_packet_forwarding_disable.value=ENABLE
kernel_kptr_restrict.status=DISABLE
kernel_kptr_restrict.value=2
fs_nr_open_limit.status=DISABLE
fs_nr_open_limit.value=786144
ipv4_packet_forwarding_disable.status=DISABLE
ipv4_packet_forwarding_disable.value=ENABLE
kernel_perf_event_paranoid.status=DISABLE
kernel_perf_event_paranoid.value=3
fs_protected_symlinks.status=DISABLE
fs_protected_symlinks.value=ENABLE
kernel_pid_max_limit.status=DISABLE
kernel_pid_max_limit.value=65536
ptrace_proc_restriction.status=DISABLE
ptrace_proc_restriction.value=2
kernel_randomize_va_space.status=DISABLE
kernel_randomize_va_space.value=2
ipv4_all_accept_redirects_disable.status=DISABLE
ipv4_all_accept_redirects_disable.value=ENABLE
ipv4_all_rp_filter_enable.status=DISABLE
ipv4_all_rp_filter_enable.value=1
ipv4_all_send_redirects_disable.status=DISABLE
ipv4_all_send_redirects_disable.value=ENABLE
fs_suid_dump_disable.status=DISABLE
fs_suid_dump_disable.value=0
tcp_syncookies_enable.status=DISABLE
tcp_syncookies_enable.value=ENABLE
tcp_keepalive_time.status=DISABLE
tcp_keepalive_time.value=300
tcp_max_syn_backlog.status=DISABLE
tcp_max_syn_backlog.value=2048
tcp_synack_retries.status=DISABLE
tcp_synack_retries.value=2
tcp_fin_timeout.status=DISABLE
tcp_fin_timeout.value=30
kernel_threads_max_limit.status=DISABLE
kernel_threads_max_limit.value=4096
user_namespace_restriction.status=DISABLE
user_namespace_restriction.value=0
