#ifndef FIC_SRC_UTILS_LOCALIZATION_MANAGER_COMPAT_H
#define FIC_SRC_UTILS_LOCALIZATION_MANAGER_COMPAT_H

#include <fic/core/LocalizationManager.h>

#endif // FIC_SRC_UTILS_LOCALIZATION_MANAGER_COMPAT_H
