#ifndef FIC_SRC_UTILS_SINGLE_LINE_FILE_HANDLER_COMPAT_H
#define FIC_SRC_UTILS_SINGLE_LINE_FILE_HANDLER_COMPAT_H

#include <fic/core/SingleLineFileHandler.h>

#endif // FIC_SRC_UTILS_SINGLE_LINE_FILE_HANDLER_COMPAT_H
